### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by john-yyb** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#22]
Hello author, I had a problem why I ran according to your method 1, a problem appeared - this dll could not be found.

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from src.FingerprintImageEnhancer import FingerprintImageEnhancer
  File "C:\Users\wrx\Desktop\SR\image-enhance\Fingerprint-Enhancement-Python-develop\src\FingerprintImageEnhancer.py", line 10, in <module>
    from scipy import signal
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\signal\__init__.py", line 322, in <module>
    from .filter_design import *
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\signal\filter_design.py", line 18, in <module>
    from scipy import special, optimize, fftpack
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\optimize\__init__.py", line 387, in <module>
    from ._minimize import *
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 117, in <module>
    from .eigen import *
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "D:\Wangluohuanjing\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: 找不到指定的程序。

**Comment by Utkarsh-Deshmukh** [comment]
Hi. sorry for the late reply. Can you try running the following:
`pip install fingerprint_enhancer`

and then in your scripts, try doing this:
```
import fingerprint_enhancer
import cv2

img = cv2.imread(<image_path>, 0)
out = fingerprint_enhancer.enhance_Fingerprint(img)
cv2.imshow('enhanced_image', out);
cv2.waitKey(0)
```
